# Generated by Django 2.0 on 2018-03-20 11:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('appliance_id', models.CharField(max_length=45, unique=True)),
                ('appliance_status', models.CharField(choices=[('y', 'On'), ('n', 'Off')], max_length=1)),
                ('last_appliance_energy_consumed', models.FloatField(null=True)),
                ('last_reading_time', models.DateTimeField()),
                ('last_water_reading', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appliance_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reading_time', models.DateTimeField(unique=True)),
                ('appliance_energy_consumed', models.FloatField(null=True)),
                ('cold_water_reading', models.FloatField(null=True)),
                ('hot_water_reading', models.FloatField(null=True)),
                ('appliance_id', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Appliance')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=45)),
                ('postcode', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('nr_Of_Floors', models.IntegerField()),
                ('building_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('floor_nr', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('time_updated', models.DateTimeField()),
                ('flat_type', models.CharField(max_length=45)),
                ('nr_of_people', models.IntegerField()),
                ('flat_rating', models.FloatField(null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Building')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List_Of_All_Appliance_in_building',
            fields=[
                ('appliance_type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('appliance_name', models.CharField(max_length=45)),
                ('appliance_power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person_Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sleep_from', models.DateTimeField()),
                ('sleep_till', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('flat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('birthdate', models.DateField()),
                ('food_preference', models.CharField(max_length=45)),
                ('last_sleep_from', models.DateTimeField()),
                ('last_sleep_till', models.DateTimeField()),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(max_length=45, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=45, null=True)),
                ('phone_nr', models.CharField(max_length=45, null=True)),
                ('flat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=45, unique=True)),
                ('room_name', models.CharField(max_length=45)),
                ('last_humidity', models.FloatField(null=True)),
                ('last_temperature', models.FloatField(null=True)),
                ('last_amount_CO2', models.FloatField(null=True)),
                ('last_reading_time', models.DateTimeField()),
                ('nr_of_appliances', models.IntegerField()),
                ('flat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField(unique=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('amount_of_CO2', models.FloatField(null=True)),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=45)),
                ('sensor_function', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_appliance', models.CharField(max_length=45)),
                ('sensor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_for', models.CharField(max_length=45)),
                ('unit', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reading_time', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('windspeed', models.IntegerField()),
                ('wind_direction', models.IntegerField()),
                ('solar_rediation', models.FloatField(null=True)),
                ('amount_of_CO2', models.FloatField(null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Building')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sensor_reading',
            name='unit_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Unit'),
        ),
        migrations.AddField(
            model_name='person_sleep',
            name='personId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.Personal_details'),
        ),
        migrations.AddField(
            model_name='appliance_reading',
            name='appliance_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.List_Of_All_Appliance_in_building'),
        ),
        migrations.AddField(
            model_name='appliance_reading',
            name='flat_id',
            field=models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat'),
        ),
        migrations.AddField(
            model_name='appliance_reading',
            name='room_id',
            field=models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Room'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_type_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatherer.List_Of_All_Appliance_in_building'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='flat_id',
            field=models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Flat'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='room_id',
            field=models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Room'),
        ),
    ]
