# Generated by Django 2.0 on 2018-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirate',
            name='country_of_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pirate',
            name='life',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pirate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pirate',
            name='years_active',
            field=models.CharField(max_length=20),
        ),
    ]
